title: Abdoul Kader Mamoudou
logo: /assets/img/IMG_0240-modified.png
description: Data scientist passionn√©e par le develeppement.
#show_downloads: true
theme: jekyll-theme-architect
waving_hand_image: /assets/img/IMG_0240-modified.png
